# action.yml
name: 'download_binary'
description: ''
inputs:
  name:
    description: ''
    required: true
    default: 'World'
  path:
    description: ''
    required: false
    default: './bin'
outputs:
  binary:
    description: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ secrets.GITHUB_TOKEN }}
    - ${{ inputs.name }}
    - ${{ inputs.path }}