name: 'environment'
description: ''
outputs:
  name:
    description: ''
    value: ${{ steps.environment.outputs.name }}
  prefix:
    description: ''
    value: ${{ steps.environment.outputs.prefix }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: environment
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "::set-output name=name::production"
          echo "::set-output name=prefix::PRODUCTION"
        else
          echo "::set-output name=name::development"
          echo "::set-output name=prefix::DEVELOPMENT"
        fi
