name: 'checkpoint'
description: 'Greet someone and record the time'
inputs:
  name:
    description: ''
    required: true
  token:
    description: ''
    required: true
outputs:
  start_time:
    description: ''
  end_time:
    description: ''
runs:
  using: 'node17'
  main: 'index.js'