name: 'checkpoint'
description: 'Greet someone and record the time'
inputs:
  name:
    description: ''
    required: true
  token:
    description: ''
    required: true
outputs:
  start_time:
    description: ''
  end_time:
    description: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.name }}
  entrypoint: '/entrypoint.sh'
  post-entrypoint: '/post-entrypoint.sh'
