name: 'window'
description: ''
inputs:
  token:
    description: ''
    required: true
outputs:
  start_time:
    description: ''
    value: ${{ steps.window.outputs.start_time }}
  end_time:
    description: ''
    value: ${{ steps.window.outputs.end_time }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: window
      run: |
        RUN_ID=${{ github.run_id }}
        RUN_NUMBER=${{ github.run_number }}

        if [[ $RUN_ID -eq 1 ]]; then
        echo "Running in a development environment locally with https://github.com/nektos/act"
        echo "::set-output name=start_time::2020-01-01T01:00:00Z"
        echo "::set-output name=end_time::2020-01-01T02:00:00Z"
        exit 0
        fi

        ABC=$(curl --silent \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ inputs.token }}" \
        https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID | jq .)

        WORKFLOW_ID=$(echo $ABC | jq -r .workflow_id)
        END_TIME=$(echo $ABC | jq -r .created_at)

        DEF=$(curl --silent \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ inputs.token }}" \
        "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$WORKFLOW_ID/runs?status=success&per_page=1&created=<$END_TIME&branch=${{ github.ref_name }}" | jq .)

        if [[ $(echo $DEF | jq -r .total_count) -eq 0 ]]; then
        START_TIME=$END_TIME
        else
        START_TIME=$(echo $DEF | jq -r .workflow_runs[].created_at)
        fi

        echo "::set-output name=start_time::$START_TIME"
        echo "::set-output name=end_time::$END_TIME"